name: Build Docker image
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/deploy-helm-gke-action

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        # Get package version from tag ref
        name: Get package version
        id: version
        run: |-
          VERSION=${GITHUB_REF#refs/tags/v}
          echo ::set-output name=full::$VERSION
          echo ::set-output name=major::${VERSION%.[0-9]*.[0-9]*}
          echo ::set-output name=minor::${VERSION%.[0-9]*}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |-
            ${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_REPO }}:v${{ steps.version.outputs.full }}
            ${{ env.DOCKER_REPO }}:v${{ steps.version.outputs.major }}
            ${{ env.DOCKER_REPO }}:v${{ steps.version.outputs.minor }}
